const LOBBY_CONFIG = {
  spotifyClientId:   'aa16f7f72c04485fb93d86d2f7ee33d1',
  spotifyRedirectUri: window.location.hostname === 'localhost'
    ? 'https://localhost:8081/callback'
    : 'https://bandmusicgames.party/callback',
};

const SONGS = [
  {
    id:       'goon',
    title:    'THE GOON SONG',
    artist:   'GOON',
    gameName: 'GRASS CUTTER 2003',
    gameUrl:  'https://forcuttinggrass.goon.bandmusicgames.party',
    trackUri: 'spotify:track:6EJAb3oTjDFwrt1dpIJPbr',
    color:    '#39ff14',
    unlocked: true,
  },
  {
    id:       'fratty',
    title:    'FRATTY PIPELINE',
    artist:   'GROUCHO BARKS',
    gameName: 'FRATTY PIPELINE',
    gameUrl:  'https://frattypipeline.grouchobarks.bandmusicgames.party',
    trackUri: 'spotify:track:33lVSu93J91BDmhfRT7iTA',
    color:    '#ff8c00',
    unlocked: true,
  },
  {
    id:       'garden',
    title:    'STAINED GRASS WINDOW',
    artist:   'GROUCHO BARKS',
    gameName: 'GARDEN',
    gameUrl:  'https://garden.grouchobarks.bandmusicgames.party',
    trackUri: 'spotify:track:5FjmryC7WxCnaeutu1XpRg',
    color:    '#a8e063',
    unlocked: true,
  },
  {
    id:       'constellation',
    title:    'FRANCIS',
    artist:   'GROUCHO BARKS',
    gameName: 'CONSTELLATION',
    gameUrl:  'https://constellation.grouchobarks.bandmusicgames.party',
    trackUri: 'spotify:track:64h0585a6LWXOdsCD2pOiW',
    color:    '#7b68ee',
    unlocked: true,
  },
  {
    id:       'thai-lunch',
    title:    'THAI LUNCH',
    artist:   'VARIOUS',
    gameName: 'THAI LUNCH',
    gameUrl:  'https://thai-lunch.bandmusicgames.party',
    trackUri: 'spotify:track:5F6r2aDjKbkaz1sNFcql5c',
    color:    '#ff4e50',
    unlocked: true,
  },
  {
    id:       'pale',
    title:    'PALE',
    artist:   '???',
    gameName: 'PALE',
    gameUrl:  'https://pale.bandmusicgames.party',
    trackUri: null,
    color:    '#c9d6df',
    unlocked: true,
  },
  {
    id:       'rust-cards',
    title:    'RUST CARDS',
    artist:   '???',
    gameName: 'RUST CARDS',
    gameUrl:  'https://rust-cards.bandmusicgames.party',
    trackUri: null,
    color:    '#ce2f39',
    unlocked: true,
  },
];
