const LOBBY_CONFIG = {
  spotifyClientId:   'aa16f7f72c04485fb93d86d2f7ee33d1',
  spotifyRedirectUri: window.location.hostname === 'localhost'
    ? 'https://localhost:8081/callback'
    : 'https://bandmusicgames.party/callback',

  // Apple Music — generate at: developer.apple.com → Certificates, Identifiers & Profiles
  // JWT signed with your .p8 private key, valid up to 6 months. Renew before expiry.
  appleMusicDeveloperToken: 'REPLACE_WITH_DEVELOPER_TOKEN',
};

const SONGS = [
  {
    id:       'goon',
    title:    'FOR CUTTING GRASS',
    artist:   'GOON',
    gameName: 'GRASS CUTTER 2003',
    gameUrl:  'https://forcuttinggrass.goon.bandmusicgames.party',
    trackUri: 'spotify:track:6EJAb3oTjDFwrt1dpIJPbr',
    appleMusicId: '1234567890',
    color:    '#39ff14',
    unlocked: true,
  },
  {
    id:       'fratty',
    title:    'FRATTY PIPELINE',
    artist:   'GROUCHO BARKS',
    gameName: 'FRATTY PIPELINE',
    gameUrl:  'https://frattypipeline.grouchobarks.bandmusicgames.party',
    trackUri: 'spotify:track:33lVSu93J91BDmhfRT7iTA',
    appleMusicId: null,
    color:    '#ff8c00',
    unlocked: true,
  },
  {
    id:       'garden',
    title:    'STAINED GRASS WINDOW',
    artist:   'GROUCHO BARKS',
    gameName: 'GARDEN',
    gameUrl:  'https://garden.grouchobarks.bandmusicgames.party',
    trackUri: 'spotify:track:5FjmryC7WxCnaeutu1XpRg',
    appleMusicId: null,
    color:    '#a8e063',
    unlocked: true,
  },
  {
    id:       'francis',
    title:    'FRANCIS',
    artist:   'DARGER',
    gameName: 'FRANCIS',
    gameUrl:  'https://francis.darger.bandmusicgames.party',
    trackUri: 'spotify:track:64h0585a6LWXOdsCD2pOiW',
    appleMusicId: null,
    color:    '#7b68ee',
    unlocked: true,
  },
  {
    id:       'thai-lunch',
    title:    'THAI LUNCH',
    artist:   'VARIOUS',
    gameName: 'THAI LUNCH',
    gameUrl:  'https://thai-lunch.bandmusicgames.party',
    trackUri: 'spotify:track:5F6r2aDjKbkaz1sNFcql5c',
    appleMusicId: null,
    color:    '#ff4e50',
    unlocked: true,
  },
  {
    id:       'pale',
    title:    'PALE',
    artist:   '???',
    gameName: 'PALE',
    gameUrl:  'https://pale.bandmusicgames.party',
    trackUri: 'spotify:track:6lrQWiXw2IMtxKJd53PhJV',
    appleMusicId: null,
    color:    '#c9d6df',
    unlocked: true,
  },
  {
    id:       'rust-cards',
    title:    'RUST CARDS',
    artist:   '???',
    gameName: 'RUST CARDS',
    gameUrl:  'https://rust-cards.bandmusicgames.party',
    trackUri: 'spotify:track:52y4KhkcAbYcogFg2u7UVP',
    appleMusicId: null,
    color:    '#ce2f39',
    unlocked: true,
  },
  {
    id:       'narasroom',
    title:    'LIZZY MCGUIRE',
    artist:   "NARA'S ROOM",
    gameName: 'HALF COURT HERO',
    gameUrl:  'https://lizzymcguire.narasroom.bandmusicgames.party',
    trackUri: 'spotify:track:7kNqAfUxLmrETcwvBTQCkg',
    appleMusicId: null, // not on Apple Music yet — update when available
    color:    '#FF1493',
    unlocked: true,
  },
];
